import "../styles/About.css";

function About() {
  return (
    <div className="about-container">

      {/* Heading */}
      <section className="about-header">
        <h1>About the Project</h1>
        <p>
          Multi-Agent Hallucination Detector and Trust Score Engine for
          Reliable AI Responses is an AI-powered system that evaluates
          responses generated by Large Language Models (LLMs). Instead of
          relying on a single AI output, our system uses multiple specialized
          agents to verify facts, analyze logical consistency, validate
          information, and calculate an overall Trust Score.
        </p>
      </section>

      {/* Objective */}
      <section className="about-card">
        <h2>🎯 Project Objective</h2>
        <p>
          The primary goal of this project is to reduce AI hallucinations by
          verifying the correctness and reliability of AI-generated responses.
          The system helps users make informed decisions by providing a Trust
          Score based on multi-agent verification.
        </p>
      </section>

      {/* Why This Project */}
      <section className="about-card">
        <h2>❓ Why is this Project Needed?</h2>

        <div className="problem-grid">

          <div className="problem-box">
            <h3>⚠ AI Hallucinations</h3>
            <p>
              AI models sometimes generate incorrect or fabricated
              information with high confidence.
            </p>
          </div>

          <div className="problem-box">
            <h3>✔ Reliable Responses</h3>
            <p>
              Multiple AI agents verify responses before they are presented
              to the user.
            </p>
          </div>

        </div>
      </section>

      {/* Workflow */}
      <section className="about-card">
        <h2>⚙ System Workflow</h2>

        <div className="workflow">

          <div className="workflow-item">User Prompt</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">AI Response</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">Fact Checker Agent</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">Logic Checker Agent</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">Validity Checker Agent</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">Trust Score Engine</div>

          <div className="workflow-arrow">↓</div>

          <div className="workflow-item">Reliable AI Response</div>

        </div>

      </section>

      {/* Technologies */}
      <section className="about-card">
        <h2>💻 Technologies Used</h2>

        <div className="tech-grid">

          <div className="tech-card">⚛ React.js</div>

          <div className="tech-card">🐍 Python</div>

          <div className="tech-card">⚡ FastAPI</div>

          <div className="tech-card">🤖 LLM APIs</div>

          <div className="tech-card">🗄 Database</div>

          <div className="tech-card">☁ Cloud Deployment</div>

        </div>

      </section>

    </div>
  );
}

export default About;